#!/bin/sh

set -eu

USER="disque"
GROUP="${USER}"

case "${1}" in
	configure)
		adduser \
			--system \
			--home /var/lib/disque \
			--quiet \
			--group \
			${USER}

		for DIR in /var/lib/disque /var/log/disque
		do
			mkdir -p ${DIR}
			chown -R ${USER}:${GROUP} ${DIR}
		done
		;;

	abort-upgrade|abort-remove|abort-deconfigure)
		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
